openapi: 3.0.0
info:
  title: Paziresh24 booking management
  version: '1.0'
  description: Management system for doctors or facilities.
  termsOfService: https://www.paziresh24.com/home/rules/
  contact:
    email: info@paziresh24.com
    name: paziresh24
    url: https://www.paziresh24.com
servers:
  - url: https://apigw.paziresh24.com/booking-management
    variables: {}
paths:
  /v1/login:
    summary: Get key to use management booking apis
    post:
      summary: Get key to use management apis
      description: ''
      operationId: ''
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                center_id:
                  type: string
              required:
                - username
                - password
                - center_id
      responses:
        '200':
          description: when api key generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      certificate:
                        type: string
      tags:
        - Auth
  /v1/appointments:
    get:
      summary: get list of appointments
      description: 'پارامتر center_id الزامی است و سایر پارامترها اختیاری هستند. در صورتی که نوبت‌های یک پزشک خاص را می‌خواهید، مقدار user_center_id یا medical_code را وارد نمایید.'
      operationId: ''
      security:
        - ApiKey: []
      parameters:
        - name: date_start
          in: query
          description: 'فرمت تاریخ ISO 8601. می‌توانید بدون ساعت هم ارسال کنید (مثال: 2023-09-19).'
          examples:
            dateTime:
              summary: 'تاریخ و ساعت'
              value: '2023-09-19T00:00:00Z'
            dateOnly:
              summary: 'فقط تاریخ'
              value: '2023-09-19'
          schema:
            oneOf:
              - type: string
                format: date-time
              - type: string
                format: date
        - name: date_end
          in: query
          description: 'فرمت تاریخ ISO 8601. می‌توانید بدون ساعت هم ارسال کنید (مثال: 2023-09-19).'
          examples:
            dateTime:
              summary: 'تاریخ و ساعت'
              value: '2023-09-19T23:59:59Z'
            dateOnly:
              summary: 'فقط تاریخ'
              value: '2023-09-19'
          schema:
            oneOf:
              - type: string
                format: date-time
              - type: string
                format: date
        - name: medical_code
          in: query
          schema:
            type: string
        - name: user_center_id
          in: query
          schema:
            type: string
            format: uuid
        - name: center_id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/appointment'
      tags:
        - Appointment
components:
  schemas:
    appointment:
      description: an appointment info
      properties:
        id:
          type: string
          format: uuid
        from:
          type: integer
          example: 1695094200
        to:
          type: integer
          example: 1695094200
        from_iso:
          type: string
          format: date-time
        to_iso:
          type: string
          format: date-time
        book_register:
          type: integer
          example: 1695094200
        reference_code:
          type: string
          example: 1695022717484
        book_status:
          type: integer
          example: 1
        paziresh_status:
          type: integer
          example: 1
        payment_status:
          type: integer
          example: 1
        patient:
          $ref: '#/components/schemas/patient'
        doctor:
          $ref: '#/components/schemas/doctor'
        center:
          $ref: '#/components/schemas/center'
        payment:
          $ref: '#/components/schemas/payment'

    patient:
      description: patient info
      properties:
        name:
          type: string
          example: علی
        family:
          type: string
          example: صدر
        cell:
          type: string
          example: 913456789
        national_code:
          type: string
          example: 1234567890
    doctor:
      description: doctor info
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: علیرضا
        family:
          type: string
          example: صدر
        medical_code:
          type: string
          example: 153815
        user_center_id:
          type: string
          format: uuid
    center:
      description: center info
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        address:
          type: string
    payment:
      description: payment info
      properties:
        book_status:
          type: string
          enum: ['paid','not-paid', 'paying', 'refunded', 'refund-request']
        factor_status:
          type: string
          enum: ['paid', 'not-paid', 'expired', 'paying', 'refunded']
        cost:
          type: integer
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-API-KEY
