openapi: 3.0.0
info:
  title: Paziresh24 booking management
  version: '1.0'
  description: Management system for doctors or facilities.
  termsOfService: https://www.paziresh24.com/home/rules/
  contact:
    email: info@paziresh24.com
    name: paziresh24
    url: https://www.paziresh24.com
servers:
  - url: https://apigw.paziresh24.com/booking-management
    variables: {}
paths:
  /v1/login:
    summary: Get key to use management booking apis
    post:
      summary: Get key to use management apis
      description: ''
      operationId: ''
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: when api key generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      certificate:
                        type: string
      tags:
        - Auth
  /v1/appointments:
    get:
      summary: get list of appointments
      description: ''
      operationId: ''
      security:
        - ApiKey: []
      parameters:
        - name: date_start
          in: query
          schema:
            type: string
            format: date-time
        - name: date_end
          in: query
          schema:
            type: string
            format: date-time
        - name: medical_code
          in: query
          schema:
            type: string
        - name: user_center_id
          in: query
          schema:
            type: string
            format: uuid
        - name: center_id
          in: query
          schema:
            type: string
            format: uuid
        - name: ref_id
          in: query
          required: false
          schema:
            type: string
          description: |
            شناسه پیگیری/رفرنس نوبت (ref_id)
            توجه: این پارامتر ممکن است برای چند نوبت مختلف یکسان باشد. برای اطمینان از بازیابی صحیح نوبت خود، پیشنهاد می‌شود علاوه‌بر ref_id، کد نظام پزشکی doctor (پارامتر medical_code) را نیز وارد کنید.
      responses:
        '200':
          description: List of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/appointment'
      tags:
        - Appointment
  /v1/appoitments/{id}:
    summary: work with specific appointment
    delete:
      summary: delete an appointment
      description: ''
      operationId: ''
      security:
        - ApiKey: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '204':
          description: when the appointment deletes successfully
      tags:
        - Appointment
  /v1/followbook:
    post:
      summary: Follow and manage booking information
      description: This endpoint allows users to retrieve booking information based on various criteria. It ensures that only appointments accessible to the user (identified by the certificate) for their authorized doctors and centers are returned.
      operationId: followBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                certificate:
                  type: string
                  description: Certificate for authentication. (Required)
                  nullable: false
                ref_id:
                  type: string
                  description: Reference ID of the booking (tracking code). (Required)
                  nullable: false
                national_code:
                  type: string
                  description: National code of the patient. (Optional)
                  nullable: true
                date:
                  type: string
                  description: Date of the booking in YYYY/MM/DD (Gregorian) or YYYY/MM/DD (Jalali) format. (Optional)
                  nullable: true
                center_id:
                  type: string
                  format: uuid
                  description: Center ID. (Optional)
                  nullable: true
                medical_code:
                  type: string
                  description: Medical code of the doctor. (Optional)
                  nullable: true
              required:
                - certificate
                - ref_id
      responses:
        '200':
          description: Successful operation. Returns the booking information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Status code (0 for success).\n                    example: 0
                  message:
                    type: string
                    description: A human-readable message.\n                    example: "Booking information retrieved successfully."
                  book:
                    $ref: '#/components/schemas/appointment'
                    description: The requested appointment details.
        '400':
          description: Bad request due to invalid or missing required parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Error status code.\n                    example: 4
                  error_message:
                    type: string
                    description: A descriptive error message.\n                    example: "Bad parameters send!"
        '401':
          description: Unauthorized due to invalid certificate.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Error status code.\n                    example: 23
                  error_message:
                    type: string
                    description: A descriptive error message.\n                    example: "Invalid certificate code!"
        '404':
          description: Book not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Error status code.\n                    example: 4
                  error_message:
                    type: string
                    description: A descriptive error message.\n                    example: "Book not found!"
      tags:
        - Booking Management
components:
  schemas:
    appointment:
      description: an appointment info
      properties:
        id:
          type: string
          format: uuid
        from:
          type: integer
          example: 1695094200
        to:
          type: integer
          example: 1695094200
        from_iso:
          type: string
          format: date-time
        to_iso:
          type: string
          format: date-time
        book_register:
          type: integer
          example: 1695094200
        reference_code:
          type: string
          example: 1695022717484
        book_status:
          type: integer
          example: 1
        paziresh_status:
          type: integer
          example: 1
        payment_status:
          type: integer
          example: 1
        patient:
          $ref: '#/components/schemas/patient'
        doctor:
          $ref: '#/components/schemas/doctor'
        center:
          $ref: '#/components/schemas/center'

    patient:
      description: patient info
      properties:
        name:
          type: string
          example: علی
        family:
          type: string
          example: صدر
        cell:
          type: string
          example: 913456789
        national_code:
          type: string
          example: 1234567890
    doctor:
      description: doctor info
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: علیرضا
        family:
          type: string
          example: صدر
        medical_code:
          type: string
          example: 153815
        user_center_id:
          type: string
          format: uuid
    center:
      description: center info
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        address:
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-API-KEY
