openapi: 3.0.0
info:
  description: "API documentation for sending push notifications to Paziresh24 users."
  version: "1"
  title: "Notification API"
  contact:
    email: dev.amirhbeigi@gmail.com
    name: Amirhossein Beigi
servers:
  - url: "https://hamdast.paziresh24.com/api/v1"
tags:
  - name: Subscribers
    description: Notification subscribers
  - name: Trigger
    description: Send notification
paths:
  /apps/{app_id}/notifications/subscribers/{user_id}/:
    get:
      summary: "Get Notification Subscribers"
      description: "This endpoint allows you to check the possibility of sending notifications to subscribers."
      tags:
        - Subscribers
      parameters:
        - in: path
          name: app_id
          required: true
          schema:
            type: string
        - in: path
          name: user_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "The user has given access to the notification."
        '404':
          description: "User not found."
        '401':
          description: "Unauthorized request due to invalid or missing authorization token."
      security:
        - authorizations: []
  /apps/{app_id}/notifications/trigger/{user_id}/:
    post:
      summary: "Send a Push Notification"
      description: "This endpoint sends a push notification to a specific Paziresh24 user."
      tags:
        - Trigger
      parameters:
        - in: path
          name: app_id
          required: true
          schema:
            type: string
        - in: path
          name: user_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: "string"
                  description: "The title of the push notification, which will appear in bold. This parameter can have a maximum of 100 characters."
                body:
                  type: "string"
                  description: "The main content of the push notification. This parameter allows a maximum of 200 characters"
                url:
                  type: "string"
                  description: "A URL that can be included in the notification to direct the user to a specific webpage."
                buttons:
                  type: "array"
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                        description: title of the button
                      url:
                        type: string
                        description: url of the button
                icon:
                  type: "string"
                  description: "A URL to an icon that can be included in the notification."
                image:
                  type: "string"
                  description: "A URL to an image that can be included in the notification."
              required:
                - title
                - text
      responses:
        '200':
          description: "The request has been accepted and the notification will be processed."
        '404':
          description: "User not found."
        '401':
          description: "Unauthorized request due to invalid or missing authorization token."
      security:
        - authorizations: []
components:
  securitySchemes:
    authorizations:
      type: apiKey
      in: header
      name: x-api-key
      description: "The `authorizations` header contains a unique token that grants access to the Paziresh24 Notification API. To obtain your authorization token, please contact our support at support@paziresh24.com."
security:
  - authorizations: []
